In [5]:
import torch
x = torch.rand(3, 1)
print(x)
h = 0
x[:-h-1, 0]

tensor([[0.6718],
        [0.4827],
        [0.6870]])


tensor([0.6718, 0.4827])

In [2]:
import torch.nn as nn
import torch
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()

In [4]:
input

tensor([[ 0.7377, -1.0159,  1.5682, -1.0578, -1.4087],
        [-1.2844,  0.9308, -2.0137, -0.4357, -1.0310],
        [ 1.3500, -0.1307,  0.5558,  0.5115,  1.0929]], requires_grad=True)